# Generated by Django 4.2.1 on 2023-05-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bnb_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='btc_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='usdt_balance',
            field=models.FloatField(default=0),
        ),
    ]
